.extern handle_interrupt
.extern handle_h_interrupt
.global interrupt
.align 4


interrupt:

    j s_interrupt
    sret

.org interrupt+36
    j h_interrupt
    sret



s_interrupt:
    addi sp,sp,-256
    .irp index 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    sd x\index, \index * 8(sp)
    .endr

    addi fp,sp,0


    call handle_interrupt

    sd a0, 10 * 8(fp) #valjda je ovde sta znam

    .irp index 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    ld x\index, \index * 8(sp)
    .endr

    addi sp,sp,256

    sret

h_interrupt:
    addi sp,sp,-256
    .irp index 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    sd x\index, \index * 8(sp)
    .endr

    addi fp,sp,0


    call handle_h_interrupt

    sd a0, 10 * 8(fp) #valjda je ovde sta znam

    .irp index 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    ld x\index, \index * 8(sp)
    .endr

    addi sp,sp,256

    sret